# @format

version: '3.9'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
  web:
    build: .
    command:
      - sh
      - scripts/django_start.sh
    volumes:
      - .:/back-end-print:latest
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
